# Generated by Django 3.2.4 on 2021-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'Published')], default='Draft', max_length=100),
        ),
    ]
